### PR TITLE
homophones

### PR DESCRIPTION
**Pull request by coolbutuseless**
This is maybe getting out-of-scope, and i won't be at all offended when this PR is rejected.

Homophones are calculated by considering the phonetic encoding of the `all_words` list.  

If 2 words have the same phonetic encoding then we consider them homophones.

Algorithms for phonetic encoding were DoubleMetaphone and Soundex.

It doesn't work too bad considering the diversity of english pronunciation, however we might have to ignore matches for any words with spaces in them.  I believe the phonetic encoding just drops all spaces and treats it as a single word - which is definitely going to give bad matches.

``` r
library(syn)
hom('great')
#>  [1] "carat"        "card"         "carried"      "carried away"
#>  [5] "carrot"       "carroty"      "carry it"     "carry out"   
#>  [9] "carry to"     "carry weight" "cart"         "cart away"   
#> [13] "carte"        "Chiaretto"    "chord"        "cord"        
#> [17] "Corot"        "corrode"      "court"        "courtier"    
#> [21] "coward"       "cowherd"      "crate"        "create"      
#> [25] "credo"        "Credo"        "creed"        "crowd"       
#> [29] "CRT"          "crud"         "cruddy"       "crude"       
#> [33] "cruet"        "cry out"      "cry to"       "cue word"    
#> [37] "curate"       "curd"         "cured"        "curried"     
#> [41] "curt"         "garotte"      "garret"       "garrote"     
#> [45] "garrotte"     "Garuda"       "gourd"        "grad"        
#> [49] "grade"        "Grade A"      "grate"        "gray out"    
#> [53] "gray-white"   "grayed"       "grayout"      "greed"       
#> [57] "greedy"       "greet"        "grid"         "grit"        
#> [61] "gritty"       "groat"        "grot"         "grotto"      
#> [65] "grout"        "guard"        "gyrate"       "key word"    
#> [69] "krait"        "Kraut"        "quart"        "quarto"      
#> [73] "queered"      "quirt"
```

<sup>Created on 2018-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### CODE REVIEW

**Comment by njtierney** [comment]
OK so I reckon go ahead and add it! 

But can you add the following:

* News bullet
* Version bump in description
* check out the test situation (it looks like it should have complete coverage, not sure why it's at 88%?)

**Comment by njtierney** [comment]
I'm going to move my thoughts earlier into an issue

**Comment by coolbutuseless** [comment]
I think this implementation is still a bit half-baked.  Retracting it until I can make it better.

**Comment by coolbutuseless** [comment]
I had a think about homophones, and by the time I found a good data source and figured out what I could do with it, I ended up having a package!

https://github.com/coolbutuseless/phon wraps the CMU pronouncing dictionary and generates:

* Homophones,
* Rhymes
* Sound-a-likes
* Syllable counts

I think this makes a good orthogonal/companion package to `syn`. i.e. syn finds new words based upon meaning, `phon` finds new words based upon sound.

**Comment by njtierney** [comment]
Love it!

**Pull request closed without merging**
